### ISSUE TITLE
Update branding

### ISSUE THREAD

**Issue by tomkrouper** [github/orchestrator#1]
Currently orchestrator shows outbrain on the web pages.

It would be ideal to make it easy to change so whoever is using it can brand it to their liking.

Maybe add some guidelines on sizes and where to put the png/gif/jpg and allow it to be dynamic.

Or failing that, just change to some octocats.

**Comment by shlomi-noach** [comment]
Will set to octocat by default
FYI if orchestrator notices "booking.com" in the uri, a booking.com logo is presented. If it notices a "outbrain.com" n the uri, an Outbrain logo is presented. 
Some companies earned a hard coded javascript if-else.
Otherwise I'm not interested in generic branding.

**Comment by shlomi-noach** [comment]
Closed via #6, #7, #8, #9
